"""baseline current schema

Revision ID: 0001_current_schema
Revises:
Create Date: 2026-08-17 04:37:46.790970
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0001_current_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('thinking_tokens', sa.Integer(), nullable=True),
    sa.Column('answer_tokens', sa.Integer(), nullable=True),
    sa.Column('total_ms', sa.Float(), nullable=True),
    sa.Column('first_token_ms', sa.Float(), nullable=True),
    sa.Column('retrieval_ms', sa.Float(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('model_calls', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('used_second_pass', sa.Boolean(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_answer_traces_recorded_at', 'answer_traces', ['recorded_at'], unique=False)
    op.create_index('idx_answer_traces_status', 'answer_traces', ['status'], unique=False)
    op.create_index(op.f('ix_answer_traces_trace_id'), 'answer_traces', ['trace_id'], unique=True)
    op.create_index(op.f('ix_answer_traces_user_id'), 'answer_traces', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('research_field', sa.String(length=100), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('paper_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_folders_user', 'folders', ['user_id'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('research_area', sa.String(length=100), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('reading_status', sa.String(length=20), nullable=True),
    sa.Column('reading_progress', sa.Float(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_papers_research_area', 'papers', ['research_area'], unique=False)
    op.create_index('idx_papers_user', 'papers', ['user_id'], unique=False)
    op.create_table('research_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('research_topic', sa.String(length=300), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('memory', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_projects_created_at'), 'research_projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_projects_title'), 'research_projects', ['title'], unique=False)
    op.create_index(op.f('ix_research_projects_user_id'), 'research_projects', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_sessions_paper', 'chat_sessions', ['paper_id'], unique=False)
    op.create_index('idx_chat_sessions_project', 'chat_sessions', ['project_id'], unique=False)
    op.create_index('idx_chat_sessions_user', 'chat_sessions', ['user_id'], unique=False)
    op.create_table('interpret_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('interpret_type', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interpret_cache_paper_type', 'interpret_cache', ['paper_id', 'interpret_type'], unique=True)
    op.create_index('idx_interpret_cache_user', 'interpret_cache', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=True),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notes_paper', 'notes', ['paper_id'], unique=False)
    op.create_index('idx_notes_user', 'notes', ['user_id'], unique=False)
    op.create_table('project_papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('analysis_card', sa.JSON(), nullable=True),
    sa.Column('reading_plan', sa.JSON(), nullable=True),
    sa.Column('reading_priority', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'paper_id', name='uq_project_paper')
    )
    op.create_index('idx_project_papers_paper', 'project_papers', ['paper_id'], unique=False)
    op.create_index('idx_project_papers_project', 'project_papers', ['project_id'], unique=False)
    op.create_table('qa_pairs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('chunk_context', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qa_pairs_paper', 'qa_pairs', ['paper_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('section_title', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tables', sa.JSON(), nullable=True),
    sa.Column('figures', sa.JSON(), nullable=True),
    sa.Column('formulas', sa.JSON(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sections_paper', 'sections', ['paper_id'], unique=False)
    op.create_table('summary_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('overview', sa.JSON(), nullable=True),
    sa.Column('methodology', sa.JSON(), nullable=True),
    sa.Column('experiments', sa.JSON(), nullable=True),
    sa.Column('contributions', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id')
    )
    op.create_index('idx_summary_cache_paper', 'summary_cache', ['paper_id'], unique=False)
    op.create_index('idx_summary_cache_user', 'summary_cache', ['user_id'], unique=False)
    op.create_table('writing_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('markdown_text', sa.Text(), nullable=True),
    sa.Column('html_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['writing_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_writing_artifacts_project_type', 'writing_artifacts', ['project_id', 'artifact_type'], unique=False)
    op.create_index('idx_writing_artifacts_updated_at', 'writing_artifacts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_writing_artifacts_artifact_type'), 'writing_artifacts', ['artifact_type'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('follow_up_questions', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_session', 'chat_messages', ['session_id'], unique=False)
    op.create_table('document_elements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('element_type', sa.String(length=30), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('page_order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('section_path', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('is_indexable', sa.Boolean(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_elements_page', 'document_elements', ['paper_id', 'page_number'], unique=False)
    op.create_index('idx_document_elements_paper', 'document_elements', ['paper_id'], unique=False)
    op.create_index('idx_document_elements_type', 'document_elements', ['paper_id', 'element_type'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('image_index', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.Float(), nullable=True),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('chart_type', sa.String(length=50), nullable=True),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('is_filtered', sa.Boolean(), nullable=True),
    sa.Column('filtered_reason', sa.String(length=200), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_images_paper', 'images', ['paper_id'], unique=False)
    op.create_index('idx_images_section', 'images', ['section_id'], unique=False)
    op.create_index('idx_images_type', 'images', ['image_type'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('csv_content', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.JSON(), nullable=True),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('markdown_path', sa.String(length=500), nullable=True),
    sa.Column('csv_path', sa.String(length=500), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('is_corrupted', sa.Boolean(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tables_paper', 'tables', ['paper_id'], unique=False)
    op.create_index('idx_tables_section', 'tables', ['section_id'], unique=False)
    op.create_table('table_cells',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('column_index', sa.Integer(), nullable=False),
    sa.Column('row_span', sa.Integer(), nullable=True),
    sa.Column('column_span', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('header_path', sa.JSON(), nullable=True),
    sa.Column('is_header', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_table_cells_position', 'table_cells', ['table_id', 'row_index', 'column_index'], unique=False)
    op.create_index('idx_table_cells_table', 'table_cells', ['table_id'], unique=False)
    op.create_table('table_structures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('page_numbers', sa.JSON(), nullable=True),
    sa.Column('page_bboxes', sa.JSON(), nullable=True),
    sa.Column('grid', sa.JSON(), nullable=True),
    sa.Column('header_rows', sa.JSON(), nullable=True),
    sa.Column('header_tree', sa.JSON(), nullable=True),
    sa.Column('row_records', sa.JSON(), nullable=True),
    sa.Column('units', sa.JSON(), nullable=True),
    sa.Column('footnotes', sa.JSON(), nullable=True),
    sa.Column('section_path', sa.JSON(), nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('is_cross_page', sa.Boolean(), nullable=True),
    sa.Column('source_table_count', sa.Integer(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id')
    )
    op.create_index('idx_table_structures_paper', 'table_structures', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_table_structures_paper', table_name='table_structures')
    op.drop_table('table_structures')
    op.drop_index('idx_table_cells_table', table_name='table_cells')
    op.drop_index('idx_table_cells_position', table_name='table_cells')
    op.drop_table('table_cells')
    op.drop_index('idx_tables_section', table_name='tables')
    op.drop_index('idx_tables_paper', table_name='tables')
    op.drop_table('tables')
    op.drop_index('idx_images_type', table_name='images')
    op.drop_index('idx_images_section', table_name='images')
    op.drop_index('idx_images_paper', table_name='images')
    op.drop_table('images')
    op.drop_index('idx_document_elements_type', table_name='document_elements')
    op.drop_index('idx_document_elements_paper', table_name='document_elements')
    op.drop_index('idx_document_elements_page', table_name='document_elements')
    op.drop_table('document_elements')
    op.drop_index('idx_chat_messages_session', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_writing_artifacts_artifact_type'), table_name='writing_artifacts')
    op.drop_index('idx_writing_artifacts_updated_at', table_name='writing_artifacts')
    op.drop_index('idx_writing_artifacts_project_type', table_name='writing_artifacts')
    op.drop_table('writing_artifacts')
    op.drop_index('idx_summary_cache_user', table_name='summary_cache')
    op.drop_index('idx_summary_cache_paper', table_name='summary_cache')
    op.drop_table('summary_cache')
    op.drop_index('idx_sections_paper', table_name='sections')
    op.drop_table('sections')
    op.drop_index('idx_qa_pairs_paper', table_name='qa_pairs')
    op.drop_table('qa_pairs')
    op.drop_index('idx_project_papers_project', table_name='project_papers')
    op.drop_index('idx_project_papers_paper', table_name='project_papers')
    op.drop_table('project_papers')
    op.drop_index('idx_notes_user', table_name='notes')
    op.drop_index('idx_notes_paper', table_name='notes')
    op.drop_table('notes')
    op.drop_index('idx_interpret_cache_user', table_name='interpret_cache')
    op.drop_index('idx_interpret_cache_paper_type', table_name='interpret_cache')
    op.drop_table('interpret_cache')
    op.drop_index('idx_chat_sessions_user', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_project', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_paper', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_research_projects_user_id'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_title'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_created_at'), table_name='research_projects')
    op.drop_table('research_projects')
    op.drop_index('idx_papers_user', table_name='papers')
    op.drop_index('idx_papers_research_area', table_name='papers')
    op.drop_table('papers')
    op.drop_index('idx_folders_user', table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_answer_traces_user_id'), table_name='answer_traces')
    op.drop_index(op.f('ix_answer_traces_trace_id'), table_name='answer_traces')
    op.drop_index('idx_answer_traces_status', table_name='answer_traces')
    op.drop_index('idx_answer_traces_recorded_at', table_name='answer_traces')
    op.drop_table('answer_traces')
    # ### end Alembic commands ###
