"""add execution runtime

Revision ID: 0002_execution_runtime
Revises: 0001_current_schema
Create Date: 2026-08-17 05:31:07.219061
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_execution_runtime'
down_revision: Union[str, None] = '0001_current_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('agent_type', sa.String(length=80), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('active_skill', sa.String(length=120), nullable=True),
    sa.Column('runtime_version', sa.String(length=40), nullable=False),
    sa.Column('max_tool_calls', sa.Integer(), nullable=False),
    sa.Column('max_model_calls', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('max_seconds', sa.Integer(), nullable=False),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('model_call_count', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_executions_project_created', 'agent_executions', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_agent_executions_status', 'agent_executions', ['status'], unique=False)
    op.create_index('idx_agent_executions_user_created', 'agent_executions', ['user_id', 'created_at'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'seq', name='uq_agent_events_execution_seq')
    )
    op.create_index('idx_agent_events_execution_created', 'agent_events', ['execution_id', 'created_at'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=160), nullable=False),
    sa.Column('tool_version', sa.String(length=40), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('side_effect_level', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'idempotency_key', name='uq_tool_calls_execution_idempotency')
    )
    op.create_index('idx_tool_calls_execution_step', 'tool_calls', ['execution_id', 'step_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tool_calls_execution_step', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index('idx_agent_events_execution_created', table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index('idx_agent_executions_user_created', table_name='agent_executions')
    op.drop_index('idx_agent_executions_status', table_name='agent_executions')
    op.drop_index('idx_agent_executions_project_created', table_name='agent_executions')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###
