"""add research notes and evidence

Revision ID: 0003_research_items
Revises: 0002_execution_runtime
Create Date: 2026-08-17 08:53:46.001737
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0003_research_items'
down_revision: Union[str, None] = '0002_execution_runtime'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['memory_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_items_project_updated', 'memory_items', ['project_id', 'updated_at'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('element_id', sa.String(length=100), nullable=True),
    sa.Column('chunk_id', sa.String(length=100), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('normalized_claim', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(length=500), nullable=False),
    sa.Column('source_authors', sa.JSON(), nullable=False),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidence_items_paper', 'evidence_items', ['paper_id'], unique=False)
    op.create_index('idx_evidence_items_project_created', 'evidence_items', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_evidence_items_project_created', table_name='evidence_items')
    op.drop_index('idx_evidence_items_paper', table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index('idx_memory_items_project_updated', table_name='memory_items')
    op.drop_table('memory_items')
    # ### end Alembic commands ###
