"""add revisioned writing documents

Revision ID: 0004_writing_documents
Revises: 0003_research_items
Create Date: 2026-08-17 09:41:48.172733
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0004_writing_documents'
down_revision: Union[str, None] = '0003_research_items'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writing_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_revision_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_writing_documents_project_updated', 'writing_documents', ['project_id', 'updated_at'], unique=False)
    op.create_table('document_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('source_execution_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['writing_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_execution_id'], ['agent_executions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version', name='uq_document_revisions_document_version')
    )
    op.create_index('idx_document_revisions_document_created', 'document_revisions', ['document_id', 'created_at'], unique=False)
    op.create_foreign_key('fk_writing_documents_current_revision', 'writing_documents', 'document_revisions', ['current_revision_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_writing_documents_current_revision', 'writing_documents', type_='foreignkey')
    op.drop_index('idx_document_revisions_document_created', table_name='document_revisions')
    op.drop_table('document_revisions')
    op.drop_index('idx_writing_documents_project_updated', table_name='writing_documents')
    op.drop_table('writing_documents')
    # ### end Alembic commands ###
