<template>
  <section class="project-info-card" aria-label="项目概览">
    <div class="info-row"><div class="info-block"><span>研究主题</span><p>{{ project.research_topic }}</p></div><div class="info-block"><span>项目资料</span><p>{{ paperCount }} 篇论文 · {{ artifactCount }} 个产物</p></div><div class="info-block"><span>状态</span><a-select :model-value="project.status" size="small" style="width: 120px" @update:model-value="value => emit('status', String(value))"><a-option v-for="(label, key) in STATUS_LABELS" :key="key" :value="key">{{ label }}</a-option></a-select></div></div>
    <div v-if="project.abstract" class="info-abstract"><span>项目摘要</span><p>{{ project.abstract }}</p></div>
  </section>
  <section v-if="workflow" class="research-workbench" aria-labelledby="workbench-title">
    <header class="workbench-heading"><div><h1 id="workbench-title">研究工作台</h1><p>选择你现在要解决的问题。三个区域可以独立使用，项目资料会在它们之间共享。</p></div><a-button type="primary" @click="emit('chat')">自由提问</a-button></header>
    <div class="workbench-areas"><article v-for="area in workflow.areas || []" :key="area.key" :class="['workbench-area', { active: activeArea === area.key }]"><button type="button" class="area-open" @click="emit('area', area.key)"><span class="area-status">{{ statusLabel(area.status) }}</span><h2>{{ area.label }}</h2><p>{{ area.description }}</p><strong>{{ area.summary }}</strong></button><a-button :type="activeArea === area.key ? 'primary' : 'secondary'" size="small" @click="emit('area', area.key)">{{ area.primary_action }}</a-button></article></div>
    <nav class="shared-resources" aria-label="项目共享资料"><strong>共享资料</strong><button v-for="item in resources" :key="item.tab" type="button" :class="{ active: activeTab === item.tab }" @click="emit('resource', item.tab)"><span>{{ item.label }}</span><small>{{ item.count }}</small></button></nav>
  </section>
</template>

<script setup lang="ts">
import { STATUS_LABELS, type ProjectWorkflowStatus, type ResearchProject } from '@/api/projects'

defineProps<{ project: ResearchProject; workflow: ProjectWorkflowStatus | null; paperCount: number; artifactCount: number; activeArea: string; activeTab: string; resources: Array<{ tab: string; label: string; count: number }> }>()
const emit = defineEmits<{ status: [status: string]; chat: []; area: [area: 'topic' | 'reading' | 'writing']; resource: [tab: string] }>()
const statusLabel = (status: 'empty' | 'active' | 'ready') => ({ empty: '尚未开始', active: '已有内容', ready: '可继续使用' }[status])
</script>

<style scoped>
.project-info-card { margin-bottom: 12px; padding: 13px 16px; border: 1px solid var(--pa-border); border-radius: 10px; background: var(--pa-surface); }.info-row { display: grid; grid-template-columns: minmax(0,2fr) 1fr auto; gap: 20px; }.info-block { min-width: 0; }.info-block > span,.info-abstract > span { color: var(--pa-muted); font-size: 11px; font-weight: 600; }.info-block p { margin: 4px 0 0; color: var(--pa-text); font-size: 14px; }.info-abstract { margin-top: 10px; padding-top: 10px; border-top: 1px solid var(--pa-border); }.info-abstract p { margin: 4px 0 0; color: var(--pa-muted); font-size: 12px; line-height: 1.5; }.research-workbench { margin-bottom: 12px; overflow: hidden; border: 1px solid var(--pa-border); border-radius: 10px; background: var(--pa-surface); }.workbench-heading { display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; padding: 13px 16px; background: var(--pa-toolbar); color: white; }.workbench-heading h1 { margin: 0 0 2px; font-size: 18px; }.workbench-heading p { margin: 0; color: oklch(0.84 0.012 65); font-size: 12px; }.workbench-areas { display: grid; grid-template-columns: repeat(3,minmax(0,1fr)); }.workbench-area { display: flex; min-width: 0; flex-direction: column; align-items: flex-start; gap: 8px; padding: 11px 14px; border-right: 1px solid var(--pa-border); }.workbench-area:last-child { border-right: 0; }.workbench-area.active { background: var(--color-primary-light-1); }.area-open { width: 100%; padding: 0; border: 0; background: transparent; color: inherit; cursor: pointer; text-align: left; }.area-status { display: inline-flex; min-height: 22px; align-items: center; padding: 0 8px; border-radius: 5px; background: var(--pa-surface-soft); color: var(--pa-muted); font-size: 11px; font-weight: 600; }.area-open h2 { margin: 7px 0 3px; font-size: 15px; }.area-open p { min-height: 34px; margin: 0 0 5px; color: var(--pa-muted); font-size: 11px; }.area-open strong { font-size: 11px; }.shared-resources { display: flex; min-height: 40px; align-items: center; gap: 4px; padding: 4px 10px; border-top: 1px solid var(--pa-border); background: var(--pa-surface-soft); }.shared-resources > strong { margin: 0 10px; color: var(--pa-muted); font-size: 12px; }.shared-resources button { display: inline-flex; min-height: 29px; align-items: center; gap: 6px; padding: 0 8px; border: 0; border-radius: 5px; background: transparent; color: var(--pa-text); cursor: pointer; font-size: 11px; }.shared-resources button:hover,.shared-resources button.active { background: var(--pa-surface); color: var(--pa-primary); }.shared-resources small { color: var(--pa-muted); }@media (max-width: 767px) { .info-row,.workbench-areas { grid-template-columns: 1fr; }.workbench-area { border-right: 0; border-bottom: 1px solid var(--pa-border); }.workbench-heading { flex-direction: column; }.shared-resources { overflow-x: auto; } }
</style>
