<template>
  <a-spin :loading="loading">
    <div v-if="!artifact" class="empty-state"><h3>从项目文献形成选题依据</h3><p>进入项目对话并提出“梳理领域地图并给出候选选题”。研究助手会交叉检索项目论文，保存研究问题、方法版图、研究空白和下一步验证动作。</p><a-button type="primary" :disabled="!hasPapers" @click="emit('chat')">进入项目对话</a-button></div>
    <article v-else class="research-map" aria-label="领域研究地图">
      <header><div><span>当前版本 v{{ artifact.version }}</span><h2>{{ artifact.title }}</h2><p>{{ content.topic_summary }}</p></div><a-button size="small" @click="emit('open', artifact)">查看完整产物</a-button></header>
      <div v-if="content.keywords.length" class="keywords" aria-label="检索关键词"><a-tag v-for="keyword in content.keywords" :key="keyword">{{ keyword }}</a-tag></div>
      <section><h3>研究问题</h3><ol v-if="content.research_questions.length" class="questions"><li v-for="(item, index) in content.research_questions" :key="index"><strong>{{ itemTitle(item, 'question', 'title') }}</strong><p v-if="item.importance">{{ item.importance }}</p></li></ol><p v-else class="muted">尚未形成研究问题。</p></section>
      <div class="columns"><section><h3>方法版图</h3><ul v-if="content.method_families.length" class="compact"><li v-for="(item, index) in content.method_families" :key="index"><strong>{{ itemTitle(item, 'name', 'method') }}</strong><span>{{ item.strengths || item.weaknesses || '待进一步比较' }}</span></li></ul><p v-else class="muted">尚无方法分类。</p></section><section><h3>关键数据集</h3><ul v-if="content.datasets.length" class="compact"><li v-for="(item, index) in content.datasets" :key="index"><strong>{{ itemTitle(item, 'name', 'dataset') }}</strong><span>{{ item.task || item.limitations || '待补充适用任务' }}</span></li></ul><p v-else class="muted">尚无数据集归纳。</p></section></div>
      <section><h3>研究空白与风险</h3><ul v-if="content.research_gaps.length" class="gaps"><li v-for="(item, index) in content.research_gaps" :key="index"><strong>{{ itemTitle(item, 'gap', 'title') }}</strong><p v-if="item.opportunity">机会：{{ item.opportunity }}</p><p v-if="item.risk">风险：{{ item.risk }}</p></li></ul><p v-else class="muted">现有证据尚不足以判断研究空白。</p></section>
      <section><h3>候选选题</h3><div v-if="content.candidate_topics.length" class="topics"><div v-for="(item, index) in content.candidate_topics" :key="index" class="topic"><span class="index">{{ index + 1 }}</span><div><strong>{{ itemTitle(item, 'title', 'question') }}</strong><p v-if="item.novelty">创新点：{{ item.novelty }}</p><p v-if="item.feasibility">可行性：{{ item.feasibility }}</p><p v-if="item.next_step">下一步：{{ item.next_step }}</p><p v-if="item.representative_papers?.length" class="sources">代表论文：{{ representativeTitles(item.representative_papers) }}</p><p v-if="item.source_ids?.length" class="sources">证据来源：{{ item.source_ids.join('、') }}</p><div class="actions"><a-button size="mini" type="primary" :loading="adoptingIndex === index" @click="emit('adopt', item, index)">设为项目方向</a-button><a-button size="mini" @click="emit('continue-search', item)">继续搜索论文</a-button></div></div></div></div><p v-else class="muted">尚未生成候选选题。</p></section>
    </article>
  </a-spin>
</template>

<script setup lang="ts">
import type { ResearchMapContent, WritingArtifactItem } from '@/api/projects'
type CandidateTopic = ResearchMapContent['candidate_topics'][number]
defineProps<{ artifact: WritingArtifactItem | null; content: ResearchMapContent; loading: boolean; hasPapers: boolean; adoptingIndex: number | null }>()
const emit = defineEmits<{ chat: []; open: [artifact: WritingArtifactItem]; adopt: [topic: CandidateTopic, index: number]; 'continue-search': [topic: CandidateTopic] }>()
const itemTitle = (item: Record<string, any>, ...keys: string[]) => keys.map(key => item[key]).find(Boolean) || '未命名条目'
const representativeTitles = (items: Array<Record<string, any>>) => items.map(item => item.title || item.paper_title || item.paper_id).filter(Boolean).join('、')
</script>

<style scoped>
.empty-state { max-width: 680px; margin: 0 auto; padding: 48px 24px; color: var(--pa-muted); text-align: center; }.empty-state h3 { margin: 0 0 8px; color: var(--pa-text); font-size: 20px; }.empty-state p { margin: 0 0 20px; line-height: 1.7; }.research-map { display: flex; flex-direction: column; gap: 24px; }.research-map > header { display: flex; align-items: flex-start; justify-content: space-between; gap: 24px; }.research-map header span { color: var(--pa-muted); font-size: 12px; }.research-map h2 { margin: 4px 0 8px; font-size: 24px; }.research-map header p { max-width: 72ch; margin: 0; color: var(--pa-muted); line-height: 1.7; }.research-map section h3 { margin: 0 0 12px; font-size: 17px; }.keywords,.actions { display: flex; flex-wrap: wrap; gap: 8px; }.columns { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 24px; }.questions { display: grid; gap: 8px; margin: 0; padding-left: 24px; }.questions li { padding: 10px 12px; border-bottom: 1px solid var(--pa-border); }.questions p,.gaps p,.topic p { margin: 4px 0 0; color: var(--pa-muted); line-height: 1.55; }.compact,.gaps { display: grid; gap: 8px; margin: 0; padding: 0; list-style: none; }.compact li { display: flex; flex-direction: column; gap: 4px; padding: 12px; border-radius: 8px; background: var(--pa-surface-soft); }.compact span { color: var(--pa-muted); }.gaps li { padding: 14px 16px; border: 1px solid var(--pa-border); border-radius: 8px; }.topics { display: grid; gap: 12px; }.topic { display: grid; grid-template-columns: 32px minmax(0, 1fr); gap: 12px; }.index { display: grid; width: 30px; height: 30px; place-items: center; border-radius: 50%; background: var(--color-primary-light-1); color: var(--pa-primary); font-weight: 700; }.sources { font-size: 12px; }.actions { margin-top: 10px; }.muted { color: var(--pa-muted); }@media (max-width: 767px) { .research-map > header { flex-direction: column; }.columns { grid-template-columns: 1fr; } }
</style>
