<template>
  <details v-if="blueprint || fullDraft || reviewReport || finalManuscript" class="lifecycle"><summary>论文蓝图、审计与导出</summary><a-spin :loading="loading"><article v-if="blueprint"><header><div><span>论文蓝图</span><h2>{{ content.working_title }}</h2><p>{{ content.central_claim }}</p></div><a-button size="small" @click="emit('open', blueprint)">查看完整蓝图</a-button></header><ol class="sections"><li v-for="section in content.sections" :key="section.section_id"><span class="order">{{ section.order }}</span><div><div class="title"><h3>{{ section.title }}</h3><span :class="`status status-${draftStatus(section.section_id)}`">{{ draftStatusLabel(section.section_id) }}</span></div><p>{{ section.purpose }}</p><div class="meta"><span>目标 {{ section.word_target }} 字</span><span>主张 {{ section.key_claims?.length||0 }}</span><span>证据 {{ section.evidence_refs?.length||0 }}</span><span>待引文 {{ section.citation_needs?.length||0 }}</span><span v-if="sectionDraft(section.section_id)?.meta?.unresolved_items?.length" class="unresolved">未解决 {{ sectionDraft(section.section_id)?.meta?.unresolved_items?.length }}</span></div></div><a-button v-if="sectionDraft(section.section_id)" size="small" @click="emit('section', section.section_id)">查看草稿</a-button></li></ol>
    <section v-if="fullDraft||reviewReport||finalManuscript" class="refinement" aria-label="全文审校状态"><header><div><h3>全文审校</h3><p>全文必须通过阻断项检查后才能定稿。</p></div><a-button v-if="fullDraft&&!reviewReport" size="small" @click="emit('chat')">开始全文审计</a-button></header><div class="flow"><button :class="{ready:!!fullDraft}" :disabled="!fullDraft" @click="fullDraft&&emit('open',fullDraft)"><span>完整草稿</span><strong>{{ fullDraft?'已组装':'未组装' }}</strong></button><button :class="{ready:!!reviewReport,blocked:reviewCounts.blocker>0}" :disabled="!reviewReport" @click="reviewReport&&emit('open',reviewReport)"><span>审计报告</span><strong v-if="reviewReport">阻断 {{ reviewCounts.blocker }} · 重要 {{ reviewCounts.major }}</strong><strong v-else>待审计</strong></button><button :class="{ready:!!finalManuscript}" :disabled="!finalManuscript" @click="finalManuscript&&emit('open',finalManuscript)"><span>论文终稿</span><strong>{{ finalManuscript?'可下载':'未定稿' }}</strong></button></div><p v-if="reviewReport&&reviewCounts.blocker>0" class="guidance">请在项目对话中按审计报告定向修订对应章节，然后重新组装并审计。</p><div v-if="finalManuscript" class="exports"><span>导出终稿</span><a-button v-for="format in formats" :key="format.key" :type="format.key==='zip'?'primary':'secondary'" size="small" :loading="exportLoading===format.key" @click="emit('download',format.key)">{{ format.label }}</a-button></div></section>
  </article></a-spin></details>
</template>
<script setup lang="ts">
import type { PaperBlueprintContent, WritingArtifactItem } from '@/api/projects'
const props=defineProps<{blueprint:WritingArtifactItem|null;content:PaperBlueprintContent;artifacts:WritingArtifactItem[];fullDraft:WritingArtifactItem|null;reviewReport:WritingArtifactItem|null;finalManuscript:WritingArtifactItem|null;reviewCounts:{blocker:number;major:number;minor:number};loading:boolean;exportLoading:'md'|'tex'|'docx'|'zip'|''}>()
const emit=defineEmits<{open:[artifact:WritingArtifactItem];section:[sectionId:string];chat:[];download:[format:'md'|'tex'|'docx'|'zip']}>()
const formats=[{key:'md',label:'下载 Markdown'},{key:'tex',label:'下载 LaTeX'},{key:'docx',label:'下载 Word'},{key:'zip',label:'下载投稿包'}] as const
const sectionDraft=(sectionId:string)=>props.artifacts.find(item=>item.artifact_type==='section_draft'&&item.parent_id===props.blueprint?.id&&item.meta?.section_id===sectionId)
const draftStatus=(sectionId:string)=>{const draft=sectionDraft(sectionId);return !draft?'pending':draft.meta?.unresolved_items?.length?'failed':'completed'}
const draftStatusLabel=(sectionId:string)=>({completed:'草稿完成',failed:'待修订',pending:'未开始'})[draftStatus(sectionId)]
</script>
<style scoped>
.lifecycle{margin-top:12px;border:1px solid var(--pa-border);border-radius:8px}.lifecycle>summary{padding:12px 14px;color:var(--pa-muted);cursor:pointer;font-size:13px}.lifecycle article{padding:16px}.lifecycle article>header,.refinement>header{display:flex;justify-content:space-between;align-items:flex-start;gap:20px}.lifecycle header>div>span{color:var(--pa-muted);font-size:12px}.lifecycle h2{margin:4px 0 8px}.lifecycle header p{margin:0;color:var(--pa-muted)}.sections{display:grid;gap:8px;margin:20px 0 0;padding:0;list-style:none}.sections>li{display:grid;grid-template-columns:32px minmax(0,1fr) auto;gap:12px;align-items:start;padding:14px;border:1px solid var(--pa-border);border-radius:8px}.order{display:grid;width:30px;height:30px;place-items:center;border-radius:50%;background:var(--color-primary-light-1);color:var(--pa-primary);font-weight:700}.title,.meta,.exports{display:flex;align-items:center;flex-wrap:wrap;gap:8px}.title h3{margin:0}.status{padding:2px 7px;border-radius:999px;background:var(--pa-surface-soft);color:var(--pa-muted);font-size:11px}.status-completed{color:var(--pa-success)}.status-failed,.unresolved{color:var(--pa-danger)}.sections p{margin:5px 0;color:var(--pa-muted)}.meta{color:var(--pa-muted);font-size:12px}.refinement{margin-top:22px;padding-top:20px;border-top:1px solid var(--pa-border)}.refinement h3{margin:0 0 4px}.flow{display:grid;grid-template-columns:repeat(3,1fr);margin-top:16px;border:1px solid var(--pa-border);border-radius:8px;overflow:hidden}.flow button{display:flex;flex-direction:column;gap:4px;padding:14px;border:0;border-right:1px solid var(--pa-border);background:var(--pa-surface-soft);color:var(--pa-muted);text-align:left}.flow button:last-child{border-right:0}.flow button.ready{background:var(--pa-surface);color:var(--pa-text);cursor:pointer}.flow button.blocked strong,.guidance{color:var(--pa-danger)}.guidance{font-size:13px}.exports{margin-top:14px}.exports>span{margin-right:auto;font-weight:600}@media(max-width:767px){.lifecycle article>header,.refinement>header{flex-direction:column}.sections>li{grid-template-columns:32px minmax(0,1fr)}.sections>li>.arco-btn{grid-column:2;justify-self:start}.flow{grid-template-columns:1fr}.flow button{border-right:0;border-bottom:1px solid var(--pa-border)}.exports>span{width:100%}}
</style>
