<template>
  <a-spin :loading="loading"><div v-if="!design" class="empty-state"><h3>用证据约束研究假设</h3><p>先生成证据矩阵，再让研究助手设计可证伪假设、变量、基线、评价指标、消融实验以及成功和失败判据。</p><a-button type="primary" :disabled="!hasEvidenceMatrix" @click="emit('chat')">进入项目对话</a-button></div>
  <article v-else class="experiment"><header><div><span>研究设计</span><h2>{{ design.title }}</h2></div><a-button size="small" @click="emit('open', design)">查看完整产物</a-button></header><section class="hypothesis"><span>研究问题</span><p>{{ designContent.research_question }}</p><span>可证伪假设</span><h3>{{ designContent.hypothesis }}</h3><p>{{ designContent.rationale }}</p></section>
    <div class="columns"><section><h3>变量与控制</h3><dl><dt>自变量</dt><dd>{{ cell(designContent.independent_variables) }}</dd><dt>因变量</dt><dd>{{ cell(designContent.dependent_variables) }}</dd><dt>控制项</dt><dd>{{ cell(designContent.controls) }}</dd></dl></section><section><h3>实验步骤</h3><ol><li v-for="step in designContent.experiment_steps" :key="step">{{ step }}</li></ol></section></div>
    <div class="columns"><section><h3>成功判据</h3><ul><li v-for="item in designContent.success_criteria" :key="item">{{ item }}</li></ul></section><section><h3>证伪判据</h3><ul><li v-for="item in designContent.falsification_criteria" :key="item">{{ item }}</li></ul></section></div>
    <section v-if="designContent.requires_empirical_results" class="results"><header><div><span>真实结果关口</span><h3>{{ results ? '结果已登记' : '等待实验输出' }}</h3></div><a-button v-if="results" size="small" @click="emit('open', results)">查看完整结果</a-button><a-button v-else type="primary" size="small" @click="emit('register-results')">登记真实结果</a-button></header><p v-if="!results" class="muted">论文蓝图和结果章节不会越过此关口。请提供实际文件、实验追踪记录、数据库导出或明确的人工报告。</p><template v-else><div class="summary"><span>运行标识<strong>{{ resultsContent.run_id }}</strong></span><span>假设结论<strong>{{ outcomeLabel(resultsContent.hypothesis_outcome) }}</strong></span><span>来源<strong>{{ resultsContent.sources.length }}</strong></span><span>指标<strong>{{ resultsContent.metrics.length }}</strong></span></div><div v-if="resultsContent.metrics.length" class="table-wrap" tabindex="0" aria-label="实验指标，可横向滚动"><table><thead><tr><th>方法</th><th>数据集/划分</th><th>指标</th><th>数值</th><th>不确定性</th><th>来源</th></tr></thead><tbody><tr v-for="(metric,index) in resultsContent.metrics" :key="`${metric.metric}-${index}`"><td>{{ metric.method||metric.baseline||'—' }}</td><td>{{ [metric.dataset,metric.split].filter(Boolean).join('/')||'—' }}</td><td>{{ metric.metric }}</td><td><strong>{{ metric.value }} {{ metric.unit||'' }}</strong></td><td>{{ metric.uncertainty||'—' }}</td><td>{{ metric.source_id }}</td></tr></tbody></table></div><div class="columns"><section><h3>结果来源</h3><ul><li v-for="source in resultsContent.sources" :key="source.source_id"><strong>[{{ source.source_id }}]</strong> {{ source.source_type }} · {{ source.locator }}<small v-if="source.checksum">SHA-256：{{ source.checksum }}</small></li></ul></section><section><h3>相对设计的偏差</h3><ul v-if="resultsContent.protocol_deviations.length"><li v-for="item in resultsContent.protocol_deviations" :key="item">{{ item }}</li></ul><p v-else class="muted">未登记协议偏差。</p></section></div></template></section><section v-else class="non-empirical"><strong>非实证研究</strong><span>当前设计明确不要求新实验结果，可以直接进入论文蓝图。</span></section>
  </article></a-spin>
</template>
<script setup lang="ts">
import type { ExperimentDesignContent, ExperimentResultsContent, WritingArtifactItem } from '@/api/projects'
defineProps<{ design: WritingArtifactItem|null; designContent: ExperimentDesignContent; results: WritingArtifactItem|null; resultsContent: ExperimentResultsContent; loading: boolean; hasEvidenceMatrix: boolean }>()
const emit=defineEmits<{chat:[];open:[artifact:WritingArtifactItem];'register-results':[]}>()
const cell=(values?:string[])=>values?.length?values.join('；'):'未报告'
const outcomeLabel=(outcome:ExperimentResultsContent['hypothesis_outcome'])=>({supported:'支持',not_supported:'不支持',mixed:'部分支持',inconclusive:'证据不足'})[outcome]
</script>
<style scoped>
.empty-state{max-width:680px;margin:0 auto;padding:48px 24px;color:var(--pa-muted);text-align:center}.empty-state h3{margin:0 0 8px;color:var(--pa-text);font-size:20px}.empty-state p{margin:0 0 20px;line-height:1.7}.experiment{display:flex;flex-direction:column;gap:24px}.experiment>header,.results>header{display:flex;justify-content:space-between;align-items:flex-start;gap:24px}.experiment header span{color:var(--pa-muted);font-size:12px}.experiment h2{margin:4px 0 8px;font-size:22px}.hypothesis,.results{padding:20px;border:1px solid var(--pa-border);border-radius:8px}.hypothesis span{display:block;margin-bottom:4px;color:var(--pa-muted);font-size:12px}.hypothesis h3{margin:4px 0 12px}.hypothesis p{margin:0 0 16px;line-height:1.65}.columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.columns h3{margin:0 0 10px}.columns ul,.columns ol{margin:0;padding-left:22px;line-height:1.7}.columns dl{display:grid;grid-template-columns:90px 1fr;gap:8px;margin:0}.columns dt{color:var(--pa-muted)}.columns dd{margin:0}.results{background:var(--pa-surface-soft)}.results h3{margin:4px 0}.muted{color:var(--pa-muted)}.summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:16px 0}.summary span{padding:10px;border-radius:6px;background:var(--pa-surface);color:var(--pa-muted);font-size:12px}.summary strong{display:block;margin-top:4px;color:var(--pa-text)}.table-wrap{overflow-x:auto;margin:16px 0;border:1px solid var(--pa-border);border-radius:8px}table{width:100%;min-width:800px;border-collapse:collapse;font-size:13px}th,td{padding:10px;border-bottom:1px solid var(--pa-border);text-align:left}.non-empirical{display:flex;gap:12px;padding:14px;border-radius:8px;background:var(--pa-surface-soft)}.non-empirical span{color:var(--pa-muted)}small{display:block;color:var(--pa-muted)}@media(max-width:767px){.experiment>header,.results>header{flex-direction:column}.columns{grid-template-columns:1fr}.summary{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
