<template>
  <a-spin :loading="loading">
    <section v-if="artifact" class="screening" aria-label="候选文献筛选台账">
      <header><div><span>研究任务书 v{{ content.research_brief_version || '—' }}</span><h2>{{ artifact.title }}</h2><p>{{ content.stopping_reason || '尚未说明检索停止条件。' }}</p></div><a-button size="small" @click="emit('open', artifact)">查看完整产物</a-button></header>
      <div class="stats" aria-label="筛选统计"><span><strong>{{ content.included_count }}</strong> 纳入</span><span><strong>{{ content.maybe_count }}</strong> 待定</span><span><strong>{{ content.excluded_count }}</strong> 排除</span><span><strong>{{ content.deduplicated_count }}</strong> 去重</span></div>
      <section><h3>检索记录</h3><ul class="runs"><li v-for="(run, index) in content.query_runs" :key="`${run.source}-${index}`"><span>{{ run.source }}</span><code>{{ run.query }}</code><strong>{{ run.result_count }} 条</strong></li></ul></section>
      <section><h3>候选论文</h3><div class="candidates"><article v-for="(candidate, index) in content.candidates" :key="`${candidate.arxiv_id || candidate.doi || candidate.title}-${index}`" :class="`decision-${candidate.decision}`"><div class="candidate-head"><span>{{ decisionLabel(candidate.decision) }}</span><strong>{{ candidate.relevance_score }}/100</strong></div><h4>{{ candidate.title }}</h4><p>{{ candidate.reason }}</p><div class="meta"><span v-if="candidate.year">{{ candidate.year }}</span><span v-if="candidate.venue">{{ candidate.venue }}</span><span v-if="candidate.arxiv_id">arXiv:{{ candidate.arxiv_id }}</span><span v-else-if="candidate.doi">DOI:{{ candidate.doi }}</span></div><div v-if="candidate.coverage?.length" class="keywords"><a-tag v-for="item in candidate.coverage" :key="item">{{ item }}</a-tag></div></article></div></section>
      <section v-if="content.coverage_summary.length"><h3>覆盖度与缺口</h3><ul class="gaps"><li v-for="(item, index) in content.coverage_summary" :key="index"><strong>{{ item.dimension || `维度 ${index + 1}` }}</strong><p>{{ item.count ?? 0 }} 篇候选<span v-if="item.gap"> · 缺口：{{ item.gap }}</span></p><p v-if="item.next_query">下一检索：<code>{{ item.next_query }}</code></p></li></ul></section>
    </section>
  </a-spin>
</template>

<script setup lang="ts">
import type { LiteratureScreeningContent, WritingArtifactItem } from '@/api/projects'
defineProps<{ artifact: WritingArtifactItem | null; content: LiteratureScreeningContent; loading: boolean }>()
const emit = defineEmits<{ open: [artifact: WritingArtifactItem] }>()
const decisionLabel = (decision: 'include' | 'exclude' | 'maybe') => ({ include: '纳入', exclude: '排除', maybe: '待定' })[decision]
</script>

<style scoped>
.screening { display: flex; flex-direction: column; gap: 24px; }.screening > header { display: flex; align-items: flex-start; justify-content: space-between; gap: 24px; }.screening header span { color: var(--pa-muted); font-size: 12px; }.screening h2 { margin: 4px 0 8px; font-size: 24px; }.screening header p { margin: 0; color: var(--pa-muted); }.screening section h3 { margin: 0 0 12px; font-size: 17px; }.stats { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; }.stats > span { padding: 14px; border: 1px solid var(--pa-border); border-radius: 8px; color: var(--pa-muted); }.stats strong { display: block; color: var(--pa-text); font-size: 22px; }.runs,.gaps { display: grid; gap: 8px; margin: 0; padding: 0; list-style: none; }.runs li { display: grid; grid-template-columns: 100px minmax(0, 1fr) auto; gap: 12px; padding: 10px 0; border-bottom: 1px solid var(--pa-border); }.runs code { overflow-wrap: anywhere; }.gaps li { padding: 14px 16px; border: 1px solid var(--pa-border); border-radius: 8px; }.gaps p { margin: 4px 0 0; color: var(--pa-muted); }.candidates { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; }.candidates article { padding: 16px; border: 1px solid var(--pa-border); border-radius: 8px; }.candidates .decision-include { border-color: oklch(0.75 0.07 145); background: oklch(0.98 0.012 145); }.candidates .decision-exclude { border-color: oklch(0.78 0.07 28); background: oklch(0.98 0.012 28); }.candidates .decision-maybe { border-color: oklch(0.80 0.07 80); background: oklch(0.98 0.014 80); }.candidate-head { display: flex; justify-content: space-between; color: var(--pa-muted); font-size: 12px; }.candidates h4 { margin: 8px 0; font-size: 16px; line-height: 1.45; }.candidates p { margin: 0 0 10px; color: var(--pa-muted); line-height: 1.55; }.meta,.keywords { display: flex; flex-wrap: wrap; gap: 6px 12px; }.meta { margin-bottom: 10px; color: var(--pa-muted); font-size: 12px; }@media (max-width: 767px) { .screening > header { flex-direction: column; }.stats { grid-template-columns: repeat(2, minmax(0, 1fr)); }.candidates { grid-template-columns: 1fr; }.runs li { grid-template-columns: 1fr; } }
</style>
